config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  resources :cities
  get 'home/index'

  namespace :api, defaults: {format: "json"} do
    namespace :v1 do
      resources :registration_numbers
    end
  end

  namespace :api, defaults: {format: "json"} do
    namespace :v1 do
      resources :states
    end
  end

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :localities
  resources :registration_numbers
  resources :states

   root 'home#index'

end

app/models/locality.rb
class Locality < ActiveRecord::Base
	belongs_to :registration_number
	

	validates :name, :registration_id, presence: true
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_is_admin?
  before_action :set_locality, only: [:show, :edit, :update, :destroy]

  # GET /localities
  # GET /localities.json
  def index
    @localities = Locality.all
  end

  # GET /localities/1
  # GET /localities/1.json
  def show
  end

  # GET /localities/new
  def new
    @locality = Locality.new
  end

  # GET /localities/1/edit
  def edit
  end

  # POST /localities
  # POST /localities.json
  def create
    @locality = Locality.new(locality_params)

    respond_to do |format|
      if @locality.save
        format.html { redirect_to @locality, notice: 'Locality was successfully created.' }
        format.json { render :show, status: :created, location: @locality }
      else
        format.html { render :new }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localities/1
  # PATCH/PUT /localities/1.json
  def update
    respond_to do |format|
      if @locality.update(locality_params)
        format.html { redirect_to @locality, notice: 'Locality was successfully updated.' }
        format.json { render :show, status: :ok, location: @locality }
      else
        format.html { render :edit }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localities/1
  # DELETE /localities/1.json
  def destroy
    @locality.destroy
    respond_to do |format|
      format.html { redirect_to localities_url, notice: 'Locality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locality
      @locality = Locality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locality_params
      params.require(:locality).permit(:name, :registration_id)
    end
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/views/localities/_form.html.erb
<%= form_for(@locality) do |f| %>
  <% if @locality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@locality.errors.count, "error") %> prohibited this locality from being saved:</h2>

      <ul>
      <% @locality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :registration_id %><br>
    <%= f.collection_select :registration_id, RegistrationNumber.all, :id, :name, prompt: "Select" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/localities/edit.html.erb
<h1>Editing Locality</h1>

<%= render 'form' %>

<%= link_to 'Show', @locality %> |
<%= link_to 'Back', localities_path %>

app/views/localities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Localities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Registration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @localities.each do |locality| %>
      <tr>
        <td><%= locality.name %></td>
        <td><%= locality.registration_id %></td>
        <td><%= link_to 'Show', locality %></td>
        <td><%= link_to 'Edit', edit_locality_path(locality) %></td>
        <td><%= link_to 'Destroy', locality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Locality', new_locality_path %>

app/views/localities/new.html.erb
<h1>New Locality</h1>

<%= render 'form' %>

<%= link_to 'Back', localities_path %>

app/views/localities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @locality.name %>
</p>

<p>
  <strong>Registration:</strong>
  <%= @locality.registration_id %>
</p>

<%= link_to 'Edit', edit_locality_path(@locality) %> |
<%= link_to 'Back', localities_path %>