config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  resources :cities
  get 'home/index'

  namespace :api, defaults: {format: "json"} do
    namespace :v1 do
      resources :registration_numbers
    end
  end

  namespace :api, defaults: {format: "json"} do
    namespace :v1 do
      resources :states
    end
  end

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :localities
  resources :registration_numbers
  resources :states

   root 'home#index'

end

app/models/registration_number.rb
class RegistrationNumber < ActiveRecord::Base
	has_many :localities, foreign_key: "registration_id"
	belongs_to :state
	validates :name, :state_id, :office, presence: true
end

app/controllers/api/v1/registration_numbers_controller.rb
module Api
	module V1
		class RegistrationNumbersController < ApplicationController
			before_action :check_access_token

			def index
				if !@user.nil?
					#access_token = params[:access_token]
					#reg_no = params[:reg_no]
                   @registration_number = RegistrationNumber.find_by_name(params[:reg_no])
                   @user.update_attributes(request_limit: @user.request_limit - 1)

			    end
		    end
		    private

		    def check_access_token
			    if params[:access_token]
				   @user = User.find_by_access_token(params[:access_token])
			    end
			      return @user
			end
		end
	end
    
end

app/controllers/registration_numbers_controller.rb
class RegistrationNumbersController < ApplicationController
before_action :authenticate_user!
  before_action :check_is_admin?

  before_action :set_registration_number, only: [:show, :edit, :update, :destroy]

  # GET /registration_numbers
  # GET /registration_numbers.json
  def index
    @registration_numbers = RegistrationNumber.all
  end

  # GET /registration_numbers/1
  # GET /registration_numbers/1.json
  def show
  end

  # GET /registration_numbers/new
  def new
    @registration_number = RegistrationNumber.new
  end

  # GET /registration_numbers/1/edit
  def edit
  end

  # POST /registration_numbers
  # POST /registration_numbers.json
  def create
    @registration_number = RegistrationNumber.new(registration_number_params)

    respond_to do |format|
      if @registration_number.save
        format.html { redirect_to @registration_number, notice: 'Registration number was successfully created.' }
        format.json { render :show, status: :created, location: @registration_number }
      else
        format.html { render :new }
        format.json { render json: @registration_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registration_numbers/1
  # PATCH/PUT /registration_numbers/1.json
  def update
    respond_to do |format|
      if @registration_number.update(registration_number_params)
        format.html { redirect_to @registration_number, notice: 'Registration number was successfully updated.' }
        format.json { render :show, status: :ok, location: @registration_number }
      else
        format.html { render :edit }
        format.json { render json: @registration_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registration_numbers/1
  # DELETE /registration_numbers/1.json
  def destroy
    @registration_number.destroy
    respond_to do |format|
      format.html { redirect_to registration_numbers_url, notice: 'Registration number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration_number
      @registration_number = RegistrationNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_number_params
      params.require(:registration_number).permit(:name, :state_id, :office)
    end
end

app/helpers/registration_numbers_helper.rb
module RegistrationNumbersHelper
end

app/views/registration_numbers/_form.html.erb
<%= form_for(@registration_number) do |f| %>
  <% if @registration_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registration_number.errors.count, "error") %> prohibited this registration_number from being saved:</h2>

      <ul>
      <% @registration_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state_id %><br>
    <%= f.collection_select :state_id, State.all, :id, :name,prompt: "Select State" %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

    <div class="field">
    <%= f.label :office %><br>
    <%= f.text_field :office %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registration_numbers/edit.html.erb
<h1>Editing Registration Number</h1>

<%= render 'form' %>

<%= link_to 'Show', @registration_number %> |
<%= link_to 'Back', registration_numbers_path %>

app/views/registration_numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Registration Numbers</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Name</th>
      <th>Office</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registration_numbers.each do |registration_number| %>
      <tr>
        <td><%= registration_number.state.name %></td>
        <td><%= registration_number.name %></td>
        <td><%= registration_number.office %></td>
        <td><%= link_to 'Show', registration_number %></td>
        <td><%= link_to 'Edit', edit_registration_number_path(registration_number) %></td>
        <td><%= link_to 'Destroy', registration_number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registration number', new_registration_number_path %>

app/views/registration_numbers/new.html.erb
<h1>New Registration Number</h1>

<%= render 'form' %>

<%= link_to 'Back', registration_numbers_path %>

app/views/registration_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @registration_number.state.name %>
</p>
<p>
  <strong>Name:</strong>
  <%= @registration_number.name %>
</p>

<p>
  <strong>Office:</strong>
  <%= @registration_number.office %>
</p>



<%= link_to 'Edit', edit_registration_number_path(@registration_number) %> |
<%= link_to 'Back', registration_numbers_path %>